# -*- coding: utf-8 -*-
# -*- coding = utf-8 -*-
# @Time : 2020/8/28 7:56 下午
# @Author : 陈达维
# @File : redisInit.py
# @Software : PyCharm
import logging

import redis
from redis import Redis

regionList=[ [ 'aq' , 'daguanqu' , 'taihuxian' , 'yixiuqu' , 'susongxian' , 'yuexixian' , 'huainingxian' , 'wangjiangxian' ,
        'tongchengshi' , 'qianshanxian' , 'yingjiangqu' ] ,
      [ 'hf' , 'baohe' , 'chaohushi' , 'lujiangxian' , 'konggangjingjishifanqu' , 'shushan' , 'luyang' , 'yaohai' ,
        'zhengwu' , 'binhuxinqu' , 'jingkai2' , 'gaoxin8' , 'xinzhan' , 'feidong' , 'feixi' , 'changfeng' ] ,
      [ 'mas' , 'bowangqu' , 'hanshanxian' , 'hexian' , 'dangtuxian' , 'huashanqu' , 'yushanqu' ] ,
      [ 'wuhu' , 'sanshanqu' , 'nanlingxian' , 'yijiangqu' , 'wuweixian' , 'fanchangxian' , 'jingjikaifaqu' ,
        'wuhuxian' , 'jinghuqu' , 'jiujiangqu' ] ,
      [ 'bj' , 'dongcheng' , 'xicheng' , 'chaoyang' , 'haidian' , 'fengtai' , 'shijingshan' , 'tongzhou' , 'changping' ,
        'daxing' , 'yizhuangkaifaqu' , 'shunyi' , 'fangshan' , 'mentougou' , 'pinggu' , 'huairou' , 'miyun' ,
        'yanqing' ] ,
      [ 'cq' , 'jiangbei' , 'yubei' , 'nanan' , 'banan' , 'shapingba' , 'jiulongpo' , 'yuzhong' , 'dadukou' ,
        'jiangjing' , 'beibei' , 'kaizhouqu' , 'wushanxian1' , 'wuxixian' , 'xiushantujiazumiaozuzizhixian' ,
        'youyangtujiazumiaozuzizhixian' , 'rongchangqu' , 'pengshuimiaozutujiazuzizhixian' , 'zhongxian' ,
        'fengjiexian' , 'dianjiangxian' , 'chengkouxian' , 'tongliang' , 'bishan' , 'hechuang' , 'changshou1' ,
        'wanzhou' , 'fuling' ] ,
      [ 'fz' , 'gulouqu3' , 'taijiangqu1' , 'jinanqu1' , 'maweiqu1' , 'cangshanqu1' , 'minhouxian' , 'lianjiangxian' ,
        'pingtanxian' , 'fuqingshi' ] ,
      [ 'quanzhou' , 'huianxian1' , 'jinjiangshi' , 'shishishi' , 'nananshi' , 'yongchunxian' , 'dehuaxian' ,
        'luojiangqu1' , 'quangangqu' , 'lichengqu1' , 'anxixian' , 'fengzequ1' , 'jinmenxian' ] ,
      [ 'xm' , 'siming' , 'huli' , 'haicang' , 'jimei' , 'xiangan' , 'tongan' ] ,
      [ 'zhangzhou' , 'longwenqu1' , 'xiangchengqu3' , 'zhangzhougang1' , 'jiaomeitaishangtouziqu1' , 'longhaishi' ,
        'changtaixian1' , 'nanjingxian1' , 'pinghexian1' , 'huaanxian' , 'zhangpuxian1' , 'dongshanxian' ,
        'zhaoanxian' , 'yunxiaoxian' ] ,
      [ 'dg' , 'nanchengqu' , 'dongchengqu' , 'wanjiangqu' , 'wanchengqu' , 'liaobuzhen1' , 'humenzhen3' ,
        'changanzhen1' , 'songshanhu' , 'houjiezhen2' , 'gaobuzhen1' , 'daojiaozhen' , 'hongmeizhen' , 'shatianzhen' ,
        'dalingshanzhen1' , 'changpingzhen' , 'dalangzhen' , 'huangjiangzhen' , 'zhangmutouzhen' , 'tangxiazhen' ,
        'qingxizhen' , 'fenggangzhen' , 'dongkengzhen' , 'qishizhen' , 'shipaizhen' , 'chashanzhen' , 'machongzhen' ,
        'henglizhen' , 'shilongzhen' , 'shijiezhen1' , 'zhongtangzhen' , 'wangniudunzhen' , 'qiaotouzhen' ,
        'xiegangzhen' ] , [ 'fs' , 'chancheng' , 'nanhai' , 'shunde' , 'sanshui1' , 'gaoming1' , 'panyu' , 'baiyun' ] ,
      [ 'gz' , 'tianhe' , 'yuexiu' , 'liwan' , 'haizhu' , 'panyu' , 'baiyun' , 'huangpugz' , 'conghua' , 'zengcheng' ,
        'huadou' , 'nansha' , 'nanhai' , 'shunde' ] ,
      [ 'hui' , 'huicheng' , 'zhongkaigaoxinjishuchanyekaifaqu' , 'huiyang' , 'dayawan' , 'huidong' , 'boluo' ] ,
      [ 'jiangmen' , 'jianghaiqu' , 'pengjiangqu' , 'xinhuiqu' , 'taishanshi' , 'heshanshi' , 'enpingshi' ,
        'kaipingshi' ] , [ 'qy' , 'fogangxian' , 'qingchengqu' , 'qingxinqu' , 'yingdeshi' , 'liannanyaozuzizhixian' ,
                           'lianshanzhuangzuyaozuzizhixian' , 'lianzhoushi' , 'yangshanxian' ] ,
      [ 'sz' , 'luohuqu' , 'futianqu' , 'nanshanqu' , 'yantianqu' , 'baoanqu' , 'longgangqu' , 'longhuaqu' ,
        'guangmingqu' , 'pingshanqu' , 'dapengxinqu' ] , [ 'zh' , 'xiangzhouqu' , 'jinwanqu' , 'doumenqu' ] ,
      [ 'zhanjiang' , 'xiashanqu' , 'chikanqu' , 'potouqu' , 'mazhangqu' , 'suixixian' , 'lianjiangshi' , 'wuchuanshi' ,
        'leizhoushi' , 'xuwenxian' ] ,
      [ 'zs' , 'xiaolanzhen' , 'banfuzhen' , 'henglanzhen' , 'minzhongzhen' , 'shenwanzhen' , 'fushazhen' ,
        'huangpuzhen' , 'sanxiangzhen' , 'sanjiaozhen' , 'dongfengzhen' , 'dongqu' , 'dongshengzhen1' , 'nantouzhen' ,
        'nanlangzhen' , 'guzhenzhen' , 'tanzhouzhen' , 'dayongzhen' , 'xiqu' , 'nanqu' , 'shiqiqu' , 'huoju' ,
        'gangkouzhen' , 'shaxizhen' , 'wuguishan' ] ,
      [ 'bh' , 'hepuxian' , 'haichengqu' , 'tieshangangqu' , 'yinhaiqu' ] , [ 'fcg' , 'gangkouqu' , 'fangchengqu' ] ,
      [ 'gl' , 'qixingqu' , 'linguiqu' , 'xiangshanqu' , 'xiufengqu' , 'diecaiqu' , 'yanshanqu' , 'guanyangxian' ,
        'guibeixinqulingchuanxian1' , 'longshenggezuzizhixian' , 'yongfuxian' , 'pinglexian' ,
        'gongchengyaozuzizhixian' , 'ziyuanxian' , 'quanzhouxian' , 'lipuxian' , 'xinganxian' , 'yangshuoxian' ] ,
      [ 'liuzhou' , 'sanjiangdongzuzizhixian' , 'chengzhongqu2' , 'liubeiqu' , 'liunanqu' , 'liuchengxian' ,
        'liujiangqu' , 'ronganxian' , 'rongshuimiaozuzizhixian' , 'yufengqu' , 'luzhaixian' ] ,
      [ 'nn' , 'qingxiuqu' , 'jiangnanqu' , 'xixiangtangqu' , 'xingningqu' , 'yongningqu' , 'liangqingqu' ,
        'wumingxian' , 'binyangxian' , 'shanglinxian' , 'mashanxian' , 'hengxian' , 'longanxian' ] ,
      [ 'lz' , 'qilihequ' , 'lanzhouxinqu' , 'chengguanqu' , 'anningqu' , 'yuzhongxian' , 'yongdengxian' ,
        'gaolanxian' , 'hongguqu' , 'xiguqu' ] ,
      [ 'gy' , 'yunyanqu' , 'baiyunqu' , 'wudangqu' , 'nanmingqu' , 'huaxiqu' , 'xifengxian' , 'kaiyangxian' ,
        'xiuwenxian' , 'qingzhenshi' , 'guanshanhuqu' ] ,
      [ 'bd' , 'laishui1' , 'zhuozhou1' , 'yixian' , 'gaobeidian1' , 'jingxiuqu' , 'lianchiqu' , 'manchengqu' ,
        'qingyuanqu' , 'xushuiqu' , 'anguoshi' , 'dingzhoushi' , 'boyexian' , 'laiyuanxian' , 'tangxian' ,
        'dingxingxian' , 'wangduxian' , 'quyangxian' , 'shunpingxian' , 'lixian1' , 'gaoyangxian' , 'fupingxian2' ] ,
      [ 'lf' , 'yanjiao' , 'xianghe' , 'guangyang' , 'anci' , 'langfangjingjijishu' , 'guan' , 'dachang' ,
        'yongqing' ] ,
      [ 'sjz' , 'yuhua1' , 'jingxingkuangqu1' , 'changan' , 'qiaoxi' , 'xinhua' , 'kaifaqu1' , 'zhengding' , 'luquan' ,
        'luancheng' , 'gaocheng' , 'yuanshixian' , 'xinjishi' , 'lingshouxian' , 'pingshan1' , 'jingxingxian' ,
        'zhaoxian' , 'shenzexian' , 'jinzhoushi' , 'gaoyixian' ] ,
      [ 'ts' , 'fengnanqu' , 'fengrunqu' , 'laotingxian' , 'guyequ' , 'kaipingqu' , 'caofeidianqu' , 'luannanxian' ,
        'luanzhoushi' , 'yutianxian' , 'lubeiqu' , 'lunanqu' , 'qiananshi' , 'qianxixian' , 'zunhuashi' ] ,
      [ 'zjk' , 'wanquanqu' , 'xiahuayuan' , 'xuanhuaqu' , 'shangyixian' , 'chongliqu1' , 'chonglixian' ,
        'kangbaoxian' , 'zhangbeixian' , 'huaianxian' , 'huailaixian' , 'qiaodongqu3' , 'qiaoxiqu3' , 'guyuanxian' ,
        'zhuoluxian' , 'weixian3' , 'chichengxian' , 'yangyuanxian' ] ,
      [ 'hk' , 'xiuyingqu2' , 'longhuaqu1' , 'meilanqu1' , 'qiongshanqu1' ] ,
      [ 'san' , 'yazhou1' , 'tianya1' , 'haitang1' , 'jiyang3' ] ,
      [ 'cs' , 'yuhua' , 'yuelu' , 'tianxin' , 'kaifu' , 'furong' , 'wangcheng' , 'ningxiang' , 'liuyang' ,
        'changshaxian' ] ,
      [ 'changde' , 'linlixian' , 'anxiangxian' , 'taoyuanxian' , 'wulingqu' , 'hanshouxian' , 'jinshishi' , 'lixian4' ,
        'shimenxian' , 'dingchengqu' ] ,
      [ 'yy' , 'yueyanglouqu' , 'yueyangxian' , 'xiangyinxian' , 'pingjiangxian' , 'junshanqu' , 'miluoshi' ,
        'yunxiqu' , 'huarongxian' , 'linxiangshi' ] ,
      [ 'zhuzhou' , 'tianyuanqu' , 'lusongqu' , 'hetangqu' , 'shifengqu' , 'lilingshi' , 'yanlingxian1' ,
        'zhuzhouxian' , 'youxian' , 'chalingxian' ] ,
      [ 'kf' , 'longtingqu' , 'qixian3' , 'lankaoxian' , 'tongxuxian' , 'xiangfuqu' , 'weishixian' , 'gulouqu6' ,
        'shunhequ1' , 'yuwangtaiqu' ] ,
      [ 'luoyang' , 'luolongqu' , 'jianxiqu' , 'xigongqu' , 'chanhehuizuqu' , 'laochengqu1' , 'yichuanxian' ,
        'yibinqu1' , 'yanshishi' , 'jiliqu' , 'mengjinxian' , 'yiyangxian' , 'songxian' , 'xinanxian' ,
        'luanchuanxian' , 'ruyangxian' , 'luoningxian' ] , [ 'xinxiang' , 'hongqiqu' , 'weibinqu2' , 'muyequ' ] ,
      [ 'xc' , 'jiananqu' , 'yuzhoushi' , 'xiangchengxian2' , 'yanlingxian' , 'changgeshi' , 'weiduqu' ] ,
      [ 'zz' , 'erqi' , 'zhengdongxinqu' , 'xingyangshi' , 'xinzhengshi' , 'shangjiequ' , 'gongyishi' , 'xinmishi' ,
        'dengfengshi' , 'zhongmuxian' , 'jingkaiqu' , 'gaoxin9' , 'hangkonggangqu' , 'zhongyuan' , 'guanchenghuizuqu' ,
        'huiji' , 'jinshui' ] ,
      [ 'zk' , 'shangshuixian' , 'taikangxian' , 'chuanhuiqu' , 'fugouxian' , 'chenqiuxian' , 'huaiyangxian' ,
        'xihuaxian' , 'danchengxian' , 'xiangchengshi' , 'luyixian' ] ,
      [ 'zmd' , 'shangcaixian' , 'pingyuxian' , 'xincaixian' , 'zhengyangxian' , 'runanxian' , 'biyangxian' ,
        'queshanxian' , 'xipingxian' , 'suipingxian' , 'yichengqu1' ] ,
      [ 'ez' , 'echengqu' , 'gediankaifaqu' , 'liangzihuqu' , 'huarongqu' ] ,
      [ 'huangshi' , 'xisaishanqu' , 'huangshigangqu' , 'yangxinxian2' , 'tieshanqu' , 'xialuqu' , 'dayeshi' ] ,
      [ 'wh' , 'jiangan' , 'jianghan' , 'qiaokou' , 'dongxihu' , 'wuchang' , 'qingshan' , 'hongshan' , 'hanyang' ,
        'donghugaoxin' , 'jiangxia' , 'caidian' , 'huangbei' , 'xinzhou' , 'zhuankoukaifaqu' , 'hannan' ] ,
      [ 'xy' , 'xiangchengqu1' , 'xiangzhouqu1' , 'fanchengqu' ] ,
      [ 'yichang' , 'xilingqu' , 'wujiagangqu' , 'yilingqu' , 'yidushi' , 'zhijiangshi' , 'dangyangshi' , 'ziguixian' ,
        'xiaotingqu' , 'dianjunqu' , 'xingshanxian' , 'yuananxian' , 'wufengtujiazuzizhixian' ,
        'changyangtujiazuzizhixian' ] ,
      [ 'hrb' , 'pingfang' , 'daowai' , 'daoli' , 'nangang' , 'xiangfang' , 'songbei' , 'shangzhishi' , 'bayanxian' ,
        'hulanqu' , 'achengqu' , 'yanshouxian' , 'yilanxian' , 'mulanxian' , 'binxian' , 'tonghexian' , 'wuchangshi' ,
        'shuangchengqu' , 'fangzhengxian' , 'zhaodongshi2' ] ,
      [ 'ganzhou' , 'zhanggongqu' , 'ganxianqu' , 'nankangqu' , 'yuduxian' , 'ruijinshi' , 'ningduxian' ,
        'shangyouxian' , 'huichangxian' , 'xinfengxian' , 'quannanxian' , 'xingguoxian' , 'dayuxian' , 'anyuanxian' ,
        'dingnanxian' , 'xunwuxian' , 'chongyixian' , 'shichengxian' , 'longnanxian' ] ,
      [ 'jiujiang' , 'xiushuixian' , 'gongqingchengshi' , 'lushanshi' , 'pengzexian' , 'deanxian' , 'chaisangqu' ,
        'wuningxian' , 'yongxiuxian' , 'xunyangqu' , 'hukouxian' , 'lianxiqu' , 'ruichangshi' , 'duchangxian' ] ,
      [ 'jian' , 'jizhouqu2' , 'qingyuanqu2' , 'jianxian' , 'jishuixian' , 'taihexian2' , 'anfuxian' , 'yongxinxian' ,
        'yongfengxian' , 'suichuanxian' , 'xiajiangxian' ] ,
      [ 'nc' , 'donghuqu' , 'nanchangxian' , 'anyixian' , 'xinjianqu' , 'wanliqu' , 'honggutan1' , 'xihuqu' ,
        'jinxianxian' , 'qingyunpuqu' , 'qingshanhuqu' , 'gaoxinqu11' , 'jingkaiqu8' ] ,
      [ 'sr' , 'shangraoxian' , 'xinzhouqu' , 'guangfengqu' ] ,
      [ 'changzhou' , 'wujinqu' , 'jintanqu' , 'zhonglouqu' , 'liyangshi' , 'tianningqu' , 'xinbeiqu' ] ,
      [ 'haimen' , 'baochang' , 'binjiang3' , 'chuanjiang' , 'haimen1' , 'haimenshi1' , 'jiangzao' , 'jinxin' ,
        'linjiang' , 'qidongshi1' , 'sanchang' , 'sanyu' , 'sijia' , 'zhangzhishan' ] ,
      [ 'ha' , 'qingjiangpuqu' , 'huaiyinqu' , 'huaianqu' , 'hongzequ' , 'lianshuixian' ] ,
      [ 'jy' , 'changjingzhen' , 'chengjiangjiedao' , 'gaoxinqu14' , 'gushanzhen' , 'huangtuzhen' , 'huashizhen' ,
        'jiangyin' , 'lingangjingjikaifaqu' , 'nanzhajiedao' , 'qingyangzhen' , 'xinqiaozhen' , 'xuxiakezhen' ,
        'yuechengzhen' , 'yuntingjiedao' , 'zhouzhuangzhen' , 'zhutangzhen' ] ,
      [ 'ks' , 'bacheng' , 'dianshanhu' , 'huaqiao' , 'jinxi' , 'kaifaqu5' , 'lujia' , 'luzhi' , 'qiandeng' ,
        'yushanchengbei' , 'yushanchengnan' , 'yushanchengxi' , 'yushangaoxinqu' , 'yushanlaochengqu' , 'zhangpu' ,
        'zhoushi' , 'zhouzhuang' ] ,
      [ 'nj' , 'gulou' , 'jianye' , 'qinhuai' , 'xuanwu' , 'yuhuatai' , 'qixia' , 'jiangning' , 'pukou' , 'liuhe' ,
        'lishui' , 'gaochun' ] ,
      [ 'nt' , 'nantongjingjijishukaifaqu' , 'qidongshi' , 'rudongxian' , 'rugaoshi' , 'chongchuanqu' , 'haianxian' ,
        'haimenqu' , 'gangzhaqu' , 'tongzhouqu' ] ,
      [ 'su' , 'gongyeyuan' , 'wuzhong' , 'gusu' , 'gaoxin1' , 'xiangcheng' , 'wujiang' , 'kunshan' ] ,
      [ 'wx' , 'binhu' , 'liangxi' , 'xinwu' , 'huishan' , 'xishan' , 'jiangyinshi' , 'yixingshi' ] ,
      [ 'xz' , 'yunlongqu' , 'gulouqu1' , 'quanshanqu' , 'tongshanqu' , 'jinshanqiaokaifaqu' , 'xinchengqu3' ,
        'jiawangqu' , 'pizhoushi' , 'xinyishi' , 'suiningxian' , 'peixian' , 'fengxian1' ] ,
      [ 'yc' , 'dongtaishi' , 'tinghuqu' , 'xiangshuixian' , 'dafengqu' , 'sheyangxian' , 'jianhuxian' , 'binhaixian' ,
        'yanduqu' , 'funingxian' ] ,
      [ 'zj' , 'dantuqu' , 'danyangshi' , 'jingkou' , 'jurong' , 'yangzhongshi' , 'runzhou' ] ,
      [ 'cc' , 'jiutaiqu' , 'erdaoqu' , 'nonganxian' , 'chaoyangqu' , 'nanguanqu' , 'shuangyangqu' , 'kuanchengqu' ,
        'dehuishi' , 'jingyuequ' , 'yushushi' , 'qichechanyekaifaqu' , 'jingkaibeiqu' , 'jingkaiqu1' , 'lvyuanqu' ,
        'gaoxinbeiqu' , 'gaoxinqu16' ] ,
      [ 'jl' , 'fengmanqu' , 'chuanyingqu' , 'changyiqu' , 'longtanqu' , 'huadianshi' , 'yongjixian' , 'panshishi' ,
        'shulanshi' , 'jiaoheshi' ] ,
      [ 'dl' , 'ganjingzi' , 'shahekou' , 'zhongshan' , 'xigang' , 'gaoxinyuanqu' , 'kaifaqudl' , 'jinzhou' ,
        'lvshunkou' , 'pulandian' , 'wafangdian' ] ,
      [ 'dd' , 'donggangshi' , 'yuanbaoqu' , 'fengchengshi' , 'kuandianmanzuzizhixian' , 'zhenxingqu' , 'zhenanqu' ] ,
      [ 'sy' , 'kangpingxian' , 'xinminshi' , 'fakuxian' , 'liaozhongqu' , 'tiexi' , 'heping1' , 'shenhe' , 'hunnan' ,
        'dadong' , 'huanggu' , 'yuhong' , 'sujiatun' , 'shenbeixinqu' ] ,
      [ 'baotou' , 'donghequ' , 'shiguaiqu' , 'qingshanqu' , 'jiuyuanqu' , 'baiyunebokuangqu' , 'kundoulunqu' ,
        'tumoteyouqi' , 'daerhanmaominganlianheqi' , 'guyangxian' , 'xitugaoxinqu' , 'binhexinqu' ] ,
      [ 'cf' , 'ningchengxian' , 'yuanbaoshanqu' , 'kalaqinqi' , 'keshiketengqi' , 'linxixian' , 'balinzuoqi' ,
        'balinyouqi' , 'wengniuteqi' , 'songshanqu' , 'alukeerqinqi' , 'hongshanqu' , 'aohanqi' , 'xinchengqu8' ] ,
      [ 'hhht' , 'helingeerxian' , 'huiminqu' , 'tumotezuoqi' , 'tuoketuoxian' , 'xinchengqu1' , 'wuchuanxian' ,
        'qingshuihexian' , 'yuquanqu' , 'saihanqu' , 'jinchuankaifaqu1' ] ,
      [ 'yinchuan' , 'xingqingqu' , 'yongningxian' , 'lingwushi' , 'xixiaqu' , 'helanxian' , 'jinfengqu' ] ,
      [ 'heze' , 'mudanqu' , 'shanxian' , 'chengwuxian' , 'dingtaoqu' , 'caoxian' , 'juyexian' , 'dongmingxian' ,
        'juanchengxian' , 'yunchengxian' ] ,
      [ 'jn' , 'lixia' , 'shizhong' , 'tianqiao' , 'licheng' , 'huaiyin' , 'gaoxin' , 'jiyang' , 'shanghe' , 'pingyin' ,
        'zhangqiu1' , 'changqing' ] ,
      [ 'jining' , 'renchengqu' , 'yanzhouqu' , 'jiaxiangxian' , 'weishanxian' , 'qufushi' , 'liangshanxian' ,
        'wenshangxian' , 'sishuixian' , 'zouchengshi' , 'jinxiangxian' , 'yutaixian' ] ,
      [ 'linyi' , 'lanshanqu' , 'luozhuangqu' , 'hedongqu' , 'mengyinxian' , 'junanxian' , 'linshuxian' , 'pingyixian' ,
        'feixian' , 'yishuixian' , 'tanchengxian' , 'yinanxian' , 'lanlingxian' ] ,
      [ 'qd' , 'shinan' , 'shibei' , 'licang' , 'laoshan' , 'huangdao' , 'chengyang' , 'jiaozhou' , 'jimo' , 'pingdu' ,
        'laixi' ] ,
      [ 'ta' , 'dongpingxian' , 'ningyangxian' , 'daiyuequ' , 'xintaishi' , 'taishanqu' , 'feichengshi' ] ,
      [ 'wf' , 'linquxian' , 'fangziqu' , 'kuiwenqu' , 'anqiushi' , 'hantingqu' , 'shouguangshi' , 'changlexian' ,
        'changyishi' , 'weichengqu' , 'zhuchengshi' , 'qingzhoushi' , 'gaomishi' , 'gaoxinjishuchanyekaifaqu' ] ,
      [ 'weihai' , 'huancuiqu' , 'jingqu1' , 'gaoqu1' , 'rongchengshi' , 'wendengqu' , 'rushanshi' ] ,
      [ 'yt' , 'zhifu' , 'laishan' , 'fushan' , 'kaifaqu4' , 'gaoxinqu' , 'mouping' , 'penglai' , 'changdaoxian' ,
        'longkou' , 'laiyang' , 'laizhou' , 'haiyang' ] ,
      [ 'zb' , 'linziqu' , 'boshanqu' , 'zhoucunqu' , 'zhangdianqu' , 'huantaixian' , 'yiyuanxian' , 'zichuanqu' ,
        'jingkaiqu5' , 'gaoxinqu7' , 'gaoqingxian' ] ,
      [ 'bz' , 'nanjiangxian' , 'bazhouqu' , 'pingchangxian' , 'enyangqu' , 'tongjiangxian' , 'zhongbaqu1' ] ,
      [ 'cd' , 'jinjiang' , 'qingyang' , 'wuhou' , 'gaoxin7' , 'chenghua' , 'jinniu' , 'tianfuxinqu' , 'gaoxinxi1' ,
        'shuangliu' , 'wenjiang' , 'pidou' , 'longquanyi' , 'xindou' , 'tianfuxinqunanqu' , 'qingbaijiang' ,
        'doujiangyan' , 'pengzhou' , 'jianyang' , 'xinjin' , 'chongzhou1' , 'dayi' , 'jintang' , 'pujiang' ,
        'qionglai' ] ,
      [ 'dy' , 'jingyangqu' , 'luojiangxian' , 'shifangshi' , 'guanghanshi' , 'mianzhushi' , 'zhongjiangxian' ] ,
      [ 'dazhou' , 'dachuanqu' , 'tongchuanqu' ] ,
      [ 'guangyuan' , 'lizhouqu' , 'jiangexian' , 'wangcangxian' , 'zhaohuaqu' , 'chaotianqu' , 'cangxixian' ,
        'qingchuanxian' ] ,
      [ 'liangshan' , 'changanpianqu' , 'chengnanpianqu1' , 'laochengpianqu' , 'ningyuanqiaopianqu' , 'qionghaipianqu' ,
        'sanchakoupianqu' , 'shizhongxinpianqu' , 'xibuxinchengpianqu' ] ,
      [ 'mianyang' , 'fuchengqu' , 'youxianqu' , 'anzhouqu' , 'jiangyoushi' , 'santaixian' ] ,
      [ 'nanchong' , 'yilongxian' , 'nanbuxian' , 'jialingqu' , 'yingshanxian' , 'penganxian' , 'xichongxian' ,
        'langzhongshi' , 'shunqingqu' , 'gaopingqu' ] ,
      [ 'sn' , 'dayingxian' , 'anjuqu' , 'shehongxian' , 'chuanshanqu' , 'pengxixian' ] ,
      [ 'yibin' , 'xingwenxian' , 'nanxiqu' , 'xuzhouqu' , 'pingshanxian1' , 'jianganxian' , 'gongxian' ,
        'junlianxian' , 'cuipingqu' , 'changningxian2' , 'gaoxian' ] ,
      [ 'baoji' , 'fengxian3' , 'fengxiangxian' , 'qianyangxian' , 'taibaixian' , 'qishanxian' , 'fufengxian' ,
        'weibinqu' , 'meixian' , 'jintaiqu' , 'longxian' , 'chencangqu' , 'linyouxian' ] ,
      [ 'hanzhong' , 'hantaiqu' , 'nanzhengqu' ] ,
      [ 'xa' , 'beilin' , 'weiyang' , 'baqiao' , 'xinchengqu' , 'lintong' , 'yanliang' , 'changan4' , 'lianhu' ,
        'yanta' , 'lantian' , 'huyiqu' , 'zhouzhi' , 'gaoling1' , 'xixianxinquxian' ] ,
      [ 'xianyang' , 'jingyangxian' , 'changwuxian' , 'liquanxian' , 'sanyuanxian' , 'qianxian' , 'xunyixian' ,
        'weichengqu2' , 'qinduqu' , 'binxian1' , 'yongshouxian' , 'chunhuaxian' , 'wugongxian' , 'yanglingqu' ,
        'xingpingshi' , 'xixianxinquxianyang' ] ,
      [ 'jz' , 'jiexiushi' , 'heshunxian' , 'taiguxian' , 'shouyangxian' , 'zuoquanxian' , 'pingyaoxian' ,
        'xiyangxian' , 'yuciqu1' , 'yushexian' , 'lingshixian' , 'qixian2' ] ,
      [ 'ty' , 'xinghualingqu' , 'yingzequ' , 'wanbolinqu' , 'xiaodianqu' , 'jiancaopingqu' , 'jinyuanqu' ,
        'yangquxian' , 'loufanxian' , 'gujiaoshi' , 'qingxuxian' ] ,
      [ 'sh' , 'pudong' , 'minhang' , 'baoshan' , 'xuhui' , 'putuo' , 'yangpu' , 'changning' , 'songjiang' , 'jiading' ,
        'huangpu' , 'jingan' , 'hongkou' , 'qingpu' , 'fengxian' , 'jinshan' , 'chongming' , 'shanghaizhoubian' ] ,
      [ 'tj' , 'heping' , 'nankai' , 'hexi' , 'hebei' , 'hedong' , 'hongqiao' , 'xiqing' , 'beichen' , 'dongli' ,
        'jinnan' , 'tanggu' , 'kaifaqutj' , 'wuqing' , 'binhaixinqu' , 'baodi' , 'jizhou' , 'haihejiaoyuyuanqu' ,
        'jinghai' ] ,
      [ 'wlmq' , 'wulumuqixian' , 'tianshanqu' , 'toutunhequ' , 'xinshiqu' , 'shuimogouqu' , 'shayibakequ' ,
        'midongqu' , 'dabanchengqu' ] ,
      [ 'dali' , 'fengyi' , 'gucheng3' , 'haidong' , 'jingkaiqu10' , 'manjiangpianqu' , 'shiqu' , 'xiaguanbeiqu' ] ,
      [ 'km' , 'wuhua' , 'panlong' , 'guandu' , 'xishan23' , 'chenggong' , 'jinning' , 'songming' , 'dongchuan' ,
        'fumin' , 'yiliang' , 'shilin' , 'xundian' , 'luquan1' , 'anning' ] ,
      [ 'hz' , 'xihu' , 'dajiangdong1' , 'qiantangxinqu' , 'xiacheng' , 'jianggan' , 'gongshu' , 'shangcheng' ,
        'binjiang' , 'yuhang' , 'xiaoshan' , 'tonglu1' , 'chunan1' , 'jiande' , 'fuyang' , 'linan' ] ,
      [ 'huzhou' , 'nanxunqu' , 'changxingxian' , 'deqingxian2' , 'wuxingqu' , 'anjixian' ] ,
      [ 'jx' , 'nanhuqu' , 'tongxiangshi' , 'jiashanxian' , 'xiuzhouqu' , 'hainingshi1' , 'haiyanxian' , 'pinghushi' ] ,
      [ 'jh' , 'dongyangshi' , 'yiwushi' , 'lanxishi' , 'wuchengqu' , 'wuyixian' , 'yongkangshi' , 'pujiangxian' ,
        'pananxian' , 'jindongqu' ] ,
      [ 'nb' , 'haishuqu1' , 'jiangbeiqu1' , 'zhenhaiqu1' , 'beilunqu1' , 'yinzhouqu2' , 'yuyaoshi' , 'cixishi' ,
        'fenghuaqu' , 'xiangshanxian' , 'ninghaixian' ] ,
      [ 'quzhou' , 'changshanxian' , 'kaihuaxian' , 'kechengqu' , 'jiangshanshi' , 'qujiangqu' , 'longyouxian' ] ,
      [ 'sx' , 'shangyuqu' , 'shengzhoushi' , 'xinchangxian' , 'keqiaoqu' , 'zhujishi' , 'yuechengqu' ] ,
      [ 'taizhou' , 'sanmenxian' , 'linhaishi' , 'xianjuxian' , 'tiantaixian' , 'jiaojiangqu' , 'wenlingshi' ,
        'yuhuanshi' , 'luqiaoqu' , 'huangyanqu' ] ,
      [ 'wz' , 'luchengqu' , 'ouhaiqu' , 'longwanqu' , 'yueqingshi' , 'ruianshi' , 'cangnanxian' , 'pingyangxian' ,
        'dongtouqu' , 'taishunxian' , 'yongjiaxian' , 'longgangshi' ] ,
      [ 'yw' , 'beiyuan' , 'chengxi3' , 'choucheng' , 'choujiang' , 'fotang' , 'futian' , 'houzhai' , 'jiangdong4' ,
        'niansanli' , 'suxi' , 'yiting' , 'yiwushi1' ] ]
cityList = ['aq', 'hf', 'mas', 'wuhu', 'bj', 'cq', 'fz', 'quanzhou', 'xm', 'zhangzhou', 'dg', 'fs', 'gz', 'hui', 'jiangmen',
'qy', 'sz', 'zh', 'zhanjiang', 'zs', 'bh', 'fcg', 'gl', 'liuzhou', 'nn', 'lz', 'gy', 'bd', 'lf', 'sjz', 'ts', 'zjk',
'hk', 'san', 'cs', 'changde', 'yy', 'zhuzhou', 'kf', 'luoyang', 'xinxiang', 'xc', 'zz', 'zk', 'zmd', 'ez',
'huangshi', 'wh', 'xy', 'yichang', 'hrb', 'ganzhou', 'jiujiang', 'jian', 'nc', 'sr', 'changzhou', 'haimen', 'ha',
'jy', 'ks', 'nj', 'nt', 'su', 'wx', 'xz', 'yc', 'zj', 'cc', 'jl', 'dl', 'dd', 'sy', 'baotou', 'cf', 'hhht',
'yinchuan', 'heze', 'jn', 'jining', 'linyi', 'qd', 'ta', 'wf', 'weihai', 'yt', 'zb', 'bz', 'cd', 'dy', 'dazhou',
'guangyuan', 'liangshan', 'mianyang', 'nanchong', 'sn', 'yibin', 'baoji', 'hanzhong', 'xa', 'xianyang', 'jz', 'ty',
'sh', 'tj', 'wlmq', 'dali', 'km', 'hz', 'huzhou', 'jx', 'jh', 'nb', 'quzhou', 'sx', 'taizhou', 'wz', 'yw']

def RedisInit():

    redisConn: Redis = redis.Redis(host="39.98.150.177", port=6379, password="cdw964930361")
    with redisConn.pipeline(transaction=False) as p:
        for city in cityList:
            p.sadd("city",city)
        for list in regionList:
            i = 1
            while i< len(list):
                p.sadd(list[0],list[i])
                i+=1
        p.execute()
    redisConn.close()

def cityInit():
    redisConn: Redis = redis.Redis(host="39.98.150.177", port=6379, password="cdw964930361")
    with redisConn.pipeline(transaction=False) as p:
        for city in cityList:
            p.sadd("city",city)
        p.execute()
    redisConn.close()
if __name__ == "__main__":  # 当程序执行时
    # 调用函数
    # 在redis中使用命令：keys * 没有120条才使用下面这行
    # RedisInit()  #除非redis崩溃或者是新安装，才需要使用一次本行

    # 在redis中使用命令： smembers city
    # 结果没有118条才调用
    cityInit()